"""empty message

Revision ID: 4c330ecd1afc
Revises: 1f4fb3be6305
Create Date: 2023-06-08 01:11:01.390869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c330ecd1afc'
down_revision = '1f4fb3be6305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('primera', 'segunda', 'tercera', 'cuarta', 'quinta', 'sexta', name='type_category'), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'neutral', name='type_gender'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
